[build-system]
requires = ["addon-odoo-wheel>=0.4"]
build-backend = "addon_odoo_wheel.builder"

# Pour éviter que pypi essaye d'utiliser le README.rst en tant que description (ce qui plante), on force le nom du
# readme minimaliste pour pypi, du coup, on est obligé de créer une section [projet], donc de fixer le name.
[project]
readme = "README_PYPI.md"
name = "mangono-addon-export_json"
dynamic = ["version"]
