{
    "name": """Messengers""",
    "summary": """Messengers integration powered by Unitsoft""",
    "category": "Extra Tools",
    "images": ["static/description/messengers_image.png"],
    "version": "19.0.0.0.1",
    "application": True,
    "author": "UnitSoft",
    "support": "",
    "website": "https://unitsoft.com.ua/",
    "license": "OPL-1",
    "price": 0,
    "currency": "EUR",
    "depends": ["mail", "base", "crm"],
    "external_dependencies": {"python": [], "bin": []},
    "data": [
        "security/us_messenger_groups.xml",
        "security/ir.model.access.csv",
        "data/messenger_data.xml",
        "data/ir_cron_data.xml",
        "data/res_partner_data.xml",
        "data/utm_data.xml",
        "views/us_messenger_job_views.xml",
        "views/us_messenger_project_views.xml",
        "views/us_messenger_operator_views.xml",
        "views/res_partner_views.xml",
        "views/res_users_view.xml",
        "views/res_config_settings.xml",
        "data/res_config_data.xml",
        "views/us_messenger_script_views.xml",
        "views/discuss_channel_views.xml",
        "views/us_messenger_menus.xml",
        "views/us_messenger_script_step.xml",
        "views/us_messenger_partner_views.xml",
        "wizard/us_messenger_discuss_operator_wizard.xml",
    ],
    "assets":{
        "web.assets_backend" : [
            "us_messenger/static/src/core/common/*",
            "us_messenger/static/src/js/*",
            'us_messenger/static/src/core/web/*',
            'us_messenger/static/src/views/**/*',
        ],
    },
    "qweb": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
}
